from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from mongoengine.base.common import get_document
from mongoengine.document import Document, EmbeddedDocument
from mongoengine.errors import ValidationError
from mongoengine.fields import StringField, ReferenceField, DateTimeField,\
    EmbeddedDocumentField

from .generators import generate_client_secret, generate_client_id
from .settings import oauth2_settings
from .validators import validate_uris


@python_2_unicode_compatible
class AbstractApplication(Document):

    """
    An Application instance represents a Client on the Authorization server.
    Usually an Application is created manually by client's developers after
    logging in on an Authorization Server.

    Fields:

    * :attr:`client_id` The client identifier issued to the client during the
                        registration process as described in :rfc:`2.2`
    * :attr:`user` ref to a Django user
    * :attr:`redirect_uris` The list of allowed redirect uri. The string
                            consists of valid URLs separated by space
    * :attr:`client_type` Client type as described in :rfc:`2.1`
    * :attr:`authorization_grant_type` Authorization flows available to the
                                       Application
    * :attr:`client_secret` Confidential secret issued to the client during
                            the registration process as described in :rfc:`2.2`
    * :attr:`name` Friendly name for the Application
    """
    CLIENT_CONFIDENTIAL = 'confidential'
    CLIENT_PUBLIC = 'public'
    CLIENT_TYPES = (
        (CLIENT_CONFIDENTIAL, _('Confidential')),
        (CLIENT_PUBLIC, _('Public')),
    )

    GRANT_AUTHORIZATION_CODE = 'authorization-code'
    GRANT_IMPLICIT = 'implicit'
    GRANT_PASSWORD = 'password'
    GRANT_CLIENT_CREDENTIALS = 'client-credentials'
    GRANT_TYPES = (
        (GRANT_AUTHORIZATION_CODE, _('Authorization code')),
        (GRANT_IMPLICIT, _('Implicit')),
        (GRANT_PASSWORD, _('Resource owner password-based')),
        (GRANT_CLIENT_CREDENTIALS, _('Client credentials')),
    )

    client_id = StringField(max_length=100, unique=True,
        default=generate_client_id)
    user = ReferenceField(settings.MONGOENGINE_USER_DOCUMENT)
    help_text = _("Allowed URIs list, space separated")
    redirect_uris = StringField(help_text=help_text)
    client_type = StringField(max_length=32, choices=CLIENT_TYPES)
    authorization_grant_type = StringField(max_length=32,
        choices=GRANT_TYPES)
    client_secret = StringField(max_length=255, default=generate_client_secret)
    name = StringField(max_length=255)

    meta = {
        'abstract': True,
        'indexes': ['client_id', 'client_secret'],
    }

    @property
    def default_redirect_uri(self):
        """
        Returns the default redirect_uri extracting the first item from
        the :attr:`redirect_uris` string
        """
        if self.redirect_uris:
            return self.redirect_uris.split().pop(0)

        assert False, "If you are using implicit, authorization_code" \
                      "or all-in-one grant_type, you must define " \
                      "redirect_uris field in your Application model"

    def redirect_uri_allowed(self, uri):
        """
        Checks if given url is one of the items in :attr:`redirect_uris` string

        :param uri: Url to check
        """
        return uri in self.redirect_uris.split()

    def clean(self):
        validate_uris(self.redirect_uris)
        if not self.redirect_uris \
            and self.authorization_grant_type \
            in (AbstractApplication.GRANT_AUTHORIZATION_CODE,
                AbstractApplication.GRANT_IMPLICIT):
            error = _('Redirect_uris could not be empty with {0} grant_type')
            raise ValidationError(error.format(self.authorization_grant_type))

    def get_absolute_url(self):
        return reverse('oauth2_provider:detail', args=[str(self.id)])

    def __str__(self):
        return self.name or self.client_id


class Application(AbstractApplication):
    pass

# Add swappable like this to not break django 1.4 compatibility
Application._meta.swappable = 'OAUTH2_PROVIDER_oauth2_settings.APPLICATION_DOCUMENT'


@python_2_unicode_compatible
class Grant(Document):

    """
    A Grant instance represents a token with a short lifetime that can
    be swapped for an access token, as described in :rfc:`4.1.2`

    Fields:

    * :attr:`user` The Django user who requested the grant
    * :attr:`code` The authorization code generated by the authorization server
    * :attr:`application` Application instance this grant was asked for
    * :attr:`expires` Expire time in seconds, defaults to
                      :data:`settings.AUTHORIZATION_CODE_EXPIRE_SECONDS`
    * :attr:`redirect_uri` Self explained
    * :attr:`scope` Required scopes, optional
    """
    user = ReferenceField(settings.MONGOENGINE_USER_DOCUMENT)
    # code comes from oauthlib
    code = StringField(max_length=255)
    application = ReferenceField(oauth2_settings.APPLICATION_DOCUMENT)
    expires = DateTimeField()
    redirect_uri = StringField(max_length=255)
    scope = StringField()

    meta = {
        'indexes': ['code'],
    }

    def is_expired(self):
        """
        Check token expiration with timezone awareness
        """
        return timezone.now() >= self.expires

    def redirect_uri_allowed(self, uri):
        return uri == self.redirect_uri

    def __str__(self):
        return self.code


@python_2_unicode_compatible
class RefreshToken(EmbeddedDocument):

    """
    A RefreshToken instance represents a token that can be swapped for a new
    access token when it expires.

    Fields:

    * :attr:`user` The Django user representing resources' owner
    * :attr:`token` Token value
    * :attr:`application` Application instance
    """
    user = ReferenceField(settings.MONGOENGINE_USER_DOCUMENT)
    token = StringField(max_length=255)
    application = ReferenceField(oauth2_settings.APPLICATION_DOCUMENT)

    def __str__(self):
        return self.token


@python_2_unicode_compatible
class AccessToken(Document):

    """
    An AccessToken instance represents the actual access token to
    access user's resources, as in :rfc:`5`.

    Fields:

    * :attr:`user` The Django user representing resources' owner
    * :attr:`token` Access token
    * :attr:`application` Application instance
    * :attr:`expires` Expire time in seconds, defaults to
                      :data:`settings.ACCESS_TOKEN_EXPIRE_SECONDS`
    * :attr:`scope` Allowed scopes
    """
    user = ReferenceField(settings.MONGOENGINE_USER_DOCUMENT)
    token = StringField(max_length=255)
    application = ReferenceField(oauth2_settings.APPLICATION_DOCUMENT)
    expires = DateTimeField()
    scope = StringField()
    refresh_token = EmbeddedDocumentField(RefreshToken)

    meta = {
        'indexes': ['token', 'refresh_token.token'],
    }

    def is_valid(self, scopes=None):
        """
        Checks if the access token is valid.

        :param scopes: An iterable containing the scopes to check or None
        """
        return not self.is_expired() and self.allow_scopes(scopes)

    def is_expired(self):
        """
        Check token expiration with timezone awareness
        """
        return timezone.now() >= self.expires

    def allow_scopes(self, scopes):
        """
        Check if the token allows the provided scopes

        :param scopes: An iterable containing the scopes to check
        """
        if not scopes:
            return True

        provided_scopes = set(self.scope.split())
        resource_scopes = set(scopes)

        return resource_scopes.issubset(provided_scopes)

    def __str__(self):
        return self.token


def get_application_doc():
    """ Return the Application document that is active in this project. """
    return get_document(oauth2_settings.APPLICATION_DOCUMENT)
